#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# this 'app_lucky_number' is intended for test only if nothing works in 'app_hello'
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_hello:
  path: /
  controller: App\Controller\View::onLoadPage
  requirements:
          _method:  GET
